### ISSUE TITLE
Reducing preflight requests

### ISSUE THREAD

**Issue by daviestar** [layer7be/vue-starter#13]
Hello,

Thank you so much for this!!

I notice [here](https://github.com/layer7be/vue-starter/blob/master/resources/assets/js/interceptors/jwtAuth.js#L25-L27) that each logged-in request requires a preflight request.   Since my app is totally behind logins, this will double the amount of requests to the server.

Would you advise against [strategy 1](https://gooroo.io/GoorooTHINK/Article/16408) in this article?  I could use Laravel method-spoofing.

Cheers.

**Comment by kcalliauw** [comment]
I haven't had any issues with options requests whatsoever. Since they are very fast and very low-overhead I cannot imagine this being a big deal for server load. Unless you are working with very low-latency connections I honestly wouldn't touch it.
More ideas are welcome on this matter.

**Comment by daviestar** [comment]
If anyone else has ended up here, the default way @kcalliauw has set up these apps works best, when the Laravel api is located at `domain.com/api` and the Vue app is at the root of `domain.com`.  

Avoiding subdomains and cross-domains avoids the pre-flight request.

I found AWS Route 53 DNS can be used to 'alias' `/api`so you can manage your servers independently for Vue app vs. API (I put my Vue app on a static CloudFront CDN, which talks to `/api` on Forge).
