### ISSUE TITLE
Browsersync not hot-reloading

### ISSUE THREAD

**Issue by enbits** [layer7be/vue-starter#19]
I run 'gulp'

and then 

cd public/
browser-sync start --server --files "js/*.js, css/*.css"

but hot-reload doesn't happen. I have to run gulp and then browser-sync again to reflect the changes.

**Comment by kcalliauw** [comment]
Hi, I have had this issue before with a simple gulp watch. Usually this means your system does not allow for this many files to be "watched" at the same time. You can change those limits but this depends heavily on your system setup. It is also not an issue with the actual code I think. If this pops up for somebody else, please reopen.
