### ISSUE TITLE
online demo?

### ISSUE THREAD

**Issue by xiaolongyuan** [layer7be/vue-starter#2]

**Comment by kcalliauw** [comment]
Hi, 

Currently there is no online demo available. The project will be updated to Vue.js 1.0.0 once that is declared stable and I will try to put up an online demo at that point.

**Comment by xiaolongyuan** [comment]
thanks.

**Comment by kcalliauw** [comment]
Online demo: 

http://vue.layer7.be/ 

(login as admin@example.com / admin)

**Comment by xiaolongyuan** [comment]
@kcalliauw 
Thank you very much.
It makes me very clear to see this demonstration project.

**Comment by devtosystems** [comment]
This login is not works.
