### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by limatheus** [layer7be/vue-starter#3]
Hi, thank you for this awesome repo

After follow all instructions i got a blank screen when i try access http://localhost:8888

Can you help me?

**Comment by kcalliauw** [comment]
Hi,

Hi, thanks for reporting this. The source of this problem was that Vueify is now already present in Elixir, so it didn't have to be pushed manually.

You can pull the new version and it should work.

Cheers,
K!

**Comment by vs0uz4** [comment]
Hi, thank you for solution.
