### ISSUE TITLE
May I ask you a question about rest.js?

### ISSUE THREAD

**Issue by xiaolongyuan** [layer7be/vue-starter#4]
rest.js  Post  

Defult:
{"name":"tom","age":"1"}

This is what I want. 
==>
name=tom&tom=1

**Comment by xiaolongyuan** [comment]
This is a method of angular.js ：

        $httpProvider.defaults.transformRequest = function (data) {
            if (data === undefined) {
                return data;
            }
            return $.param(data);
        }

        $httpProvider.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded; charset=UTF-8';

**Comment by xiaolongyuan** [comment]
defaultRequest: {
      headers: {
        //'X-Requested-With': 'rest.js',
        //'Content-Type': 'application/json'
        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
      }
    }

**Comment by xiaolongyuan** [comment]
Return response is not automatically resolved

![image](https://cloud.githubusercontent.com/assets/3142363/10723663/272dfd34-7bf8-11e5-8e43-e5bf44b51049.png)

**Comment by kcalliauw** [comment]
Hey, ping me on the Vue.js chat, I'm not sure I understand the question.

https://gitter.im/vuejs/vue

**Comment by xiaolongyuan** [comment]
I'm sorry my English is not good.I'm not going to use rest.js.The document is too bad.

**Comment by xiaolongyuan** [comment]
The default configuration of the POST request body into a json.

**Comment by xiaolongyuan** [comment]
@kcalliauw 
I want :
![image](https://cloud.githubusercontent.com/assets/3142363/10724202/78414fbe-7bfd-11e5-97bd-68ccb5a47991.png)

This is not what I want:
![image](https://cloud.githubusercontent.com/assets/3142363/10724223/b190b4f8-7bfd-11e5-8bdf-1b9e0ed5b9d9.png)

**Comment by xiaolongyuan** [comment]
client({
                    path: '/oauth2/accessToken?grant_type=password&client_id=10003&client_secret=asdfghjklmnbvcxz123456',
                    entity: {
                        username: that.username,
                        password: that.password,
                    },
                    headers :{
                        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
                    }
                })
