### ISSUE TITLE
Is blacklist cleaning necessary?

### ISSUE THREAD

**Issue by ryanwinchester** [layer7be/vue-starter#5]
With single-use token flow the blacklist seems like it would grow large pretty quickly

Does this list get cleaned out automatically or will we need to set up a cron or something to do this?

Or does it matter? Just let it grow forever? Not sure how this works.

Thanks.

**Comment by kcalliauw** [comment]
Hi,

I'm on holiday right now, I'll check how that works exactly when I get back on Wednesday. Until then you may also check out the jwt-auth github page and issues.

Met vriendelijke groeten,
Koen Calliauw
Layer7 BVBA

Op 30 okt. 2015 om 19:19 heeft Ryan Winchester <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


With single-use token flow the blacklist seems like it would grow large pretty quickly

Does this list get cleaned out automatically or will we need to set up a cron or something to do this?

-

**Comment by coding-sunshine** [comment]
I am also getting following error when I click on Dog menu after logging in,
```
{"message":"The token has been blacklisted","status_code":401,"debug":{"line":36,"file":"\/Applications
\/MAMP\/htdocs\/experiments\/vue-starter\/backend\/vendor\/tymon\/jwt-auth\/src\/Middleware\/Authenticate
.php" ...
```

Am I doing something wrong in setup?

**Comment by kcalliauw** [comment]
@ryanwinchester I dug into the code of JWT a bit and it looks like it's just using the laravel configured cache backend, which by default is set to file based storage. I'm not sure if it would be necessary to clean this out manually. It looks like a TTL is added:

```php
    // in vendor/tymon/jwt-auth/src/Providers/Storage/Illuminate.php

    /**
     * Add a new item into storage
     *
     * @param  string  $key
     * @param  mixed  $value
     * @param  int  $minutes
     *
     * @return void
     */
    public function add($key, $value, $minutes)
    {
        $this->cache()->put($key, $value, $minutes);
    }
```

@coding-sunshine Are you still experiencing this? I just tested the basic installation instructions and they seem to work for me when installed from scratch. If you are still having issues, please open a new issue.
